name: Deploy Production (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # needed to push to this repo's gh-pages

concurrency:
  group: pages-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to this repo's gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./          # change to ./dist if you add a build step
          force_orphan: true
          exclude_assets: |
            .github
            .gitignore
            README.md
            LICENSE
